### PR TITLE
Update dependencies and remove minor version restrictions

### PR DESCRIPTION
**Pull request by lairtonlelis**
### What problem does this solve?

Issue number: (if applicable)

### Checklist

- [ ] I have added unit tests to cover my changes.
- [ ] I have added documentation to cover my changes.
- [ ] My changes have passed unit tests and have been tested E2E in an example project.

### CODE REVIEW

**Comment by gmile** [comment]
Merging this would be really nice. I'm failing to install ex_prom currently, because of minor version restrictions.

**Comment by gmile** [comment]
FWIW, we ended up using `telemetry` + `telemetry_metrics` + `telemetry_metrics_prometheus` combination

**Comment by shubie** [comment]
When can we make progress with is?

**Comment by hkrutzer** [comment]
@akoutmos any chance for a release with these changes? 🙂

**Pull request closed without merging**
