### PR TITLE
Remove stale suggested changes for a Broadway pipeline from the docs

### LINKED ISSUE #114: PromEx.Plugins.Broadway assigns "acknowledger" name to message metrics tag rather than module name
From
https://github.com/akoutmos/prom_ex/blob/3557e828cf3905adaf6719003e68b65294b62288/lib/prom_ex/plugins/broadway.ex#L248

This populates the `name` tag with the module name of my producer module, eg. in my code `App.Producers.TestProducer`

It conflicts with the expectation the dashboard has, that message metrics are reported with the name of the Broadway module, eg. in my example code this is filtered with the value `App.Broadway` and shows no data.

image

image

I don't know if there is a different idea at play here than matching the metrics with the processing module, but it seems that the same information is not readily available. Does this need a PR in Broadway to include additional information?

The same issue is present for exception info;
https://github.com/akoutmos/prom_ex/blob/3557e828cf3905adaf6719003e68b65294b62288/lib/prom_ex/plugins/broadway.ex#L347

Edit: I see the batch tag extraction gets the `topology_name` - is there a way to get the same passed to the messages metrics handler?

### PR DESCRIPTION
**Pull request by maxmarcon**
This commit removes the suggested changes for a Broadway pipeline that are currently in the docs. 

The docs state that the changes are necessary to correctly capture per-message metrics and error rate, but this is no longer true. No additional acknowledger needs to be added to an existing and already working Broadway pipeline since d76956385c5622096c88b33545c3998f7cc16de8.
Applying these changes to a pipeline is not needed anymore  and might very well lead to a broken pipeline as detailed in https://github.com/akoutmos/prom_ex/issues/114#issuecomment-1122369781 .

@akoutmos: my suggestion is to release a new version soon. The currently released hex version (which is older than d76956385c5622096c88b33545c3998f7cc16de8) contains misleading documentation: the suggested changes to the acknowledger, although necessary, will also lead to https://github.com/akoutmos/prom_ex/issues/114#issuecomment-1122369781.

Closes #114

### CODE REVIEW

**Comment by akoutmos** [comment]
What setup did you have in place when you validated this? Unless things changed internally in Broadway, I recall not needing the custom ack when using a GenStage producer, but this broke down when you used RMQ or Kafka. I would love to drop this work around...but I want to first validate that it works with things beyond just GenStage producers.

**Comment by maxmarcon** [comment]
> What setup did you have in place when you validated this?

1. I used the GenStage producer that comes with the example applications. You can change the topology `name` config [here](https://github.com/akoutmos/prom_ex/blob/master/example_applications/web_app/lib/web_app/temp_processor.ex#L10) and verify that this is the value actually used to extract the topology name in all message- and batch-related events ([here](https://github.com/akoutmos/prom_ex/blob/eb7023193ee5fbc89cf47b287d7a5431bad6014a/lib/prom_ex/plugins/broadway.ex#L354) and [here](https://github.com/akoutmos/prom_ex/blob/eb7023193ee5fbc89cf47b287d7a5431bad6014a/lib/prom_ex/plugins/broadway.ex#L361))

2. I also tested it with my BroadwaySQS data ingestion pipeline:

image

Messages are corrently accounted for without having to overwrite the native acknowledger.

>Unless things changed internally in Broadway, I recall not needing the custom ack when using a GenStage producer, but this broke down when you used RMQ or Kafka

Don't know how Broadway used to work when you last looked at it, but currently the exact opposite is true. You need a custom acknowledger when using a GenStage producer: https://hexdocs.pm/broadway/custom-producers.html (this is also what your example application does).
On the other hand, RMQ, Kafka and AmazonSQS all come with their own acknowledgers. For example, here's where RabbitMQ's acknwoledger is implemented: https://github.com/dashbitco/broadway_rabbitmq/blob/main/lib/broadway_rabbitmq/producer.ex#L562
These producers need their own acknowledger in order to mark the messages as handled in their queues. Carelessly overwriting this acknowledger, as the current PromEx documentation suggests, will result in a broken pipeline. Plus, as I mentioned, the overwriting is not needed anymore

**Comment by akoutmos** [comment]
Awesome! Thanks for validating this with something beyond just the example GenStage version!

**Comment by moniquelive** [comment]
In my RabbitMQ topology if I remove the `transformer:` config and `ack` and `transform` functions from my pipeline nothing is reported on Grafana... What am I missing?

**Comment by maxmarcon** [comment]
@moniquelive are you using the latest hex release or master? If you're using the hex release, then you still need to mess around with the `transformer` option and the acknowledgers. The commit that renders this unnecessary is https://github.com/akoutmos/prom_ex/commit/d76956385c5622096c88b33545c3998f7cc16de8, not released yet.

**Comment by moniquelive** [comment]
I'm using the release one. I'll be patient. I promise 🤞🏻

**Comment by m0rt3nlund** [comment]
Hi!
Any idea when this fix will be released? 
Using BroadwayKafka and PromEx does not work without messing with the acknowledger.

Thanks for a great library!

**Comment by moniquelive** [comment]
No releases for over a year... Any forecast?

**Pull request merged**
